# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QPLmainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QTableView,
    QToolBar, QVBoxLayout, QWidget)
import QPLresources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(889, 768)
        MainWindow.setToolTipDuration(5000)
        self.actionNew_Entry = QAction(MainWindow)
        self.actionNew_Entry.setObjectName(u"actionNew_Entry")
        icon = QIcon()
        icon.addFile(u":/icons/SVG/Entry-new.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew_Entry.setIcon(icon)
        self.actionNew_Entry.setMenuRole(QAction.MenuRole.NoRole)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u":/icons/SVG/document-open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setMenuRole(QAction.MenuRole.NoRole)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon2 = QIcon()
        icon2.addFile(u":/icons/SVG/preferences-system.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPreferences.setIcon(icon2)
        self.actionPreferences.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon3 = QIcon()
        icon3.addFile(u":/icons/SVG/floppy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setMenuRole(QAction.MenuRole.NoRole)
        self.actionAddEntry = QAction(MainWindow)
        self.actionAddEntry.setObjectName(u"actionAddEntry")
        icon4 = QIcon()
        icon4.addFile(u":/icons/SVG/apply.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAddEntry.setIcon(icon4)
        self.actionAddEntry.setMenuRole(QAction.MenuRole.NoRole)
        self.actionAstro = QAction(MainWindow)
        self.actionAstro.setObjectName(u"actionAstro")
        icon5 = QIcon()
        icon5.addFile(u":/icons/SVG/Sextantcolor.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAstro.setIcon(icon5)
        self.actionAstro.setMenuRole(QAction.MenuRole.NoRole)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        icon6 = QIcon()
        icon6.addFile(u":/icons/SVG/Entry-edit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionEdit.setIcon(icon6)
        self.actionEdit.setMenuRole(QAction.MenuRole.NoRole)
        self.actionDelete_Entry = QAction(MainWindow)
        self.actionDelete_Entry.setObjectName(u"actionDelete_Entry")
        icon7 = QIcon()
        icon7.addFile(u":/icons/SVG/Entry-delete.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete_Entry.setIcon(icon7)
        self.actionDelete_Entry.setMenuRole(QAction.MenuRole.NoRole)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionQuit.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionAdd = QAction(MainWindow)
        self.actionAdd.setObjectName(u"actionAdd")
        icon8 = QIcon()
        icon8.addFile(u":/icons/SVG/document-add.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAdd.setIcon(icon8)
        self.actionAdd.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSort = QAction(MainWindow)
        self.actionSort.setObjectName(u"actionSort")
        icon9 = QIcon()
        icon9.addFile(u":/icons/SVG/sort-clean.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSort.setIcon(icon9)
        self.actionSort.setMenuRole(QAction.MenuRole.NoRole)
        self.actionstartstopp = QAction(MainWindow)
        self.actionstartstopp.setObjectName(u"actionstartstopp")
        self.actionstartstopp.setCheckable(True)
        self.actionstartstopp.setChecked(True)
        icon10 = QIcon()
        icon10.addFile(u":/icons/SVG/button-red.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon10.addFile(u":/icons/SVG/button-green.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionstartstopp.setIcon(icon10)
        self.actionstartstopp.setMenuRole(QAction.MenuRole.NoRole)
        self.actionDeadReconing = QAction(MainWindow)
        self.actionDeadReconing.setObjectName(u"actionDeadReconing")
        icon11 = QIcon()
        icon11.addFile(u":/icons/SVG/deadreconing.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDeadReconing.setIcon(icon11)
        self.actionDeadReconing.setMenuRole(QAction.MenuRole.NoRole)
        self.actionPrintPDF = QAction(MainWindow)
        self.actionPrintPDF.setObjectName(u"actionPrintPDF")
        icon12 = QIcon()
        icon12.addFile(u":/icons/SVG/print-PDF.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrintPDF.setIcon(icon12)
        self.actionPrintPDF.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.logTableView = QTableView(self.centralwidget)
        self.logTableView.setObjectName(u"logTableView")

        self.verticalLayout.addWidget(self.logTableView)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 889, 37))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew_Entry)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPrintPDF)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionSort)
        self.toolBar.addAction(self.actionNew_Entry)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionAddEntry)
        self.toolBar.addAction(self.actionDelete_Entry)
        self.toolBar.addAction(self.actionAstro)
        self.toolBar.addAction(self.actionDeadReconing)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addAction(self.actionstartstopp)

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew_Entry.setText(QCoreApplication.translate("MainWindow", u"New Entry", None))
#if QT_CONFIG(tooltip)
        self.actionNew_Entry.setToolTip(QCoreApplication.translate("MainWindow", u"Create new empty Entry", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionNew_Entry.setStatusTip(QCoreApplication.translate("MainWindow", u"Create new empty Entry", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionNew_Entry.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("MainWindow", u"Open a logfile replacing the current log.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOpen.setStatusTip(QCoreApplication.translate("MainWindow", u"Open a logfile replacing the current log.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionPreferences.setToolTip(QCoreApplication.translate("MainWindow", u"Open Preferences", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPreferences.setStatusTip(QCoreApplication.translate("MainWindow", u"Open Preferences Dialog", None))
#endif // QT_CONFIG(statustip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the log into monthly files", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave.setStatusTip(QCoreApplication.translate("MainWindow", u"Save the log into monthly files", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionAddEntry.setText(QCoreApplication.translate("MainWindow", u"AddEntry", None))
#if QT_CONFIG(tooltip)
        self.actionAddEntry.setToolTip(QCoreApplication.translate("MainWindow", u"Add new entry with values from from SK server", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAddEntry.setStatusTip(QCoreApplication.translate("MainWindow", u"Add new entry with values from from SK server", None))
#endif // QT_CONFIG(statustip)
        self.actionAstro.setText(QCoreApplication.translate("MainWindow", u"Astro", None))
#if QT_CONFIG(tooltip)
        self.actionAstro.setToolTip(QCoreApplication.translate("MainWindow", u"Open Celestial Navigation dialog", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAstro.setStatusTip(QCoreApplication.translate("MainWindow", u"Open Celestial Navigation dialog", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionAstro.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Celestial Navigation</span></p><p>Provides a dialog create a new logbook entry based on Sextant measurements.</p><p>You will need a basic understanding of navigation by the stars for this to be usefull.</p><p><br/></p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
#if QT_CONFIG(tooltip)
        self.actionEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Edit Log Entry", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionEdit.setStatusTip(QCoreApplication.translate("MainWindow", u"Edit Log Entry", None))
#endif // QT_CONFIG(statustip)
        self.actionDelete_Entry.setText(QCoreApplication.translate("MainWindow", u"Delete Entry", None))
#if QT_CONFIG(tooltip)
        self.actionDelete_Entry.setToolTip(QCoreApplication.translate("MainWindow", u"Delete log entry", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionDelete_Entry.setStatusTip(QCoreApplication.translate("MainWindow", u"Delete log entry", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionDelete_Entry.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
#if QT_CONFIG(tooltip)
        self.actionAdd.setToolTip(QCoreApplication.translate("MainWindow", u"Add Logbook file to the current log", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAdd.setStatusTip(QCoreApplication.translate("MainWindow", u"Add Logbook file to the current log", None))
#endif // QT_CONFIG(statustip)
        self.actionSort.setText(QCoreApplication.translate("MainWindow", u"Sort Clean", None))
#if QT_CONFIG(tooltip)
        self.actionSort.setToolTip(QCoreApplication.translate("MainWindow", u"Sort entrys and remove dublicates", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSort.setStatusTip(QCoreApplication.translate("MainWindow", u"Sort entrys and remove dublicates", None))
#endif // QT_CONFIG(statustip)
        self.actionstartstopp.setText(QCoreApplication.translate("MainWindow", u"startstopp", None))
#if QT_CONFIG(tooltip)
        self.actionstartstopp.setToolTip(QCoreApplication.translate("MainWindow", u"Start/Stopp automatic entrys", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionstartstopp.setStatusTip(QCoreApplication.translate("MainWindow", u"Start/Stopp automatic entrys", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionstartstopp.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionDeadReconing.setText(QCoreApplication.translate("MainWindow", u"Dead Reconing", None))
#if QT_CONFIG(tooltip)
        self.actionDeadReconing.setToolTip(QCoreApplication.translate("MainWindow", u"Calculate new dead reconing position", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionDeadReconing.setStatusTip(QCoreApplication.translate("MainWindow", u"Calculate new dead reconing position", None))
#endif // QT_CONFIG(statustip)
        self.actionPrintPDF.setText(QCoreApplication.translate("MainWindow", u"PrintPDF", None))
#if QT_CONFIG(tooltip)
        self.actionPrintPDF.setToolTip(QCoreApplication.translate("MainWindow", u"Export Logbook to PDF", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPrintPDF.setStatusTip(QCoreApplication.translate("MainWindow", u"Export Logbook to PDF", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionPrintPDF.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(statustip)
        self.toolBar.setStatusTip("")
#endif // QT_CONFIG(statustip)
    # retranslateUi

